/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AGENDA_H_RPCGEN
#define _AGENDA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct contato {
	char *nome;
	char *endereco;
	int telefone;
	struct contato *next;
};
typedef struct contato contato;

#define AGENDA_PROG 1111111
#define AGENDA_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define INSERE 1
extern  int * insere_1(contato *, CLIENT *);
extern  int * insere_1_svc(contato *, struct svc_req *);
#define CONSULTA 2
extern  contato * consulta_1(char **, CLIENT *);
extern  contato * consulta_1_svc(char **, struct svc_req *);
#define ALTERA 3
extern  int * altera_1(contato *, CLIENT *);
extern  int * altera_1_svc(contato *, struct svc_req *);
#define REMOVER 4
extern  int * remover_1(char **, CLIENT *);
extern  int * remover_1_svc(char **, struct svc_req *);
extern int agenda_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INSERE 1
extern  int * insere_1();
extern  int * insere_1_svc();
#define CONSULTA 2
extern  contato * consulta_1();
extern  contato * consulta_1_svc();
#define ALTERA 3
extern  int * altera_1();
extern  int * altera_1_svc();
#define REMOVER 4
extern  int * remover_1();
extern  int * remover_1_svc();
extern int agenda_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_contato (XDR *, contato*);

#else /* K&R C */
extern bool_t xdr_contato ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AGENDA_H_RPCGEN */
