/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "agenda.h"

bool_t
xdr_contato (XDR *xdrs, contato *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->nome, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->endereco, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->telefone))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->erro))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (contato), (xdrproc_t) xdr_contato))
		 return FALSE;
	return TRUE;
}
